/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.docs.guidebook.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.docs.guidebook.model.Guidebook;
import com.docs.guidebook.model.GuidebookModel;
import com.docs.guidebook.model.GuidebookSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Guidebook service. Represents a row in the &quot;GB_Guidebook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>GuidebookModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GuidebookImpl}.
 * </p>
 *
 * @author liferay
 * @see GuidebookImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class GuidebookModelImpl
	extends BaseModelImpl<Guidebook> implements GuidebookModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a guidebook model instance should use the <code>Guidebook</code> interface instead.
	 */
	public static final String TABLE_NAME = "GB_Guidebook";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"guidebookId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("guidebookId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table GB_Guidebook (uuid_ VARCHAR(75) null,guidebookId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table GB_Guidebook";

	public static final String ORDER_BY_JPQL =
		" ORDER BY guidebook.guidebookId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY GB_Guidebook.guidebookId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.docs.guidebook.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.docs.guidebook.model.Guidebook"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.docs.guidebook.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.docs.guidebook.model.Guidebook"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.docs.guidebook.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.docs.guidebook.model.Guidebook"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long GUIDEBOOKID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Guidebook toModel(GuidebookSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Guidebook model = new GuidebookImpl();

		model.setUuid(soapModel.getUuid());
		model.setGuidebookId(soapModel.getGuidebookId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Guidebook> toModels(GuidebookSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Guidebook> models = new ArrayList<Guidebook>(soapModels.length);

		for (GuidebookSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.docs.guidebook.service.util.ServiceProps.get(
			"lock.expiration.time.com.docs.guidebook.model.Guidebook"));

	public GuidebookModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _guidebookId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGuidebookId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _guidebookId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Guidebook.class;
	}

	@Override
	public String getModelClassName() {
		return Guidebook.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Guidebook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Guidebook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Guidebook, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Guidebook)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Guidebook, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Guidebook, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Guidebook)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Guidebook, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Guidebook, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Guidebook>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Guidebook.class.getClassLoader(), Guidebook.class,
			ModelWrapper.class);

		try {
			Constructor<Guidebook> constructor =
				(Constructor<Guidebook>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Guidebook, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Guidebook, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Guidebook, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Guidebook, Object>>();
		Map<String, BiConsumer<Guidebook, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Guidebook, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object uuid) {
					guidebook.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"guidebookId",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getGuidebookId();
				}

			});
		attributeSetterBiConsumers.put(
			"guidebookId",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object guidebookId) {
					guidebook.setGuidebookId((Long)guidebookId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object groupId) {
					guidebook.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object companyId) {
					guidebook.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object userId) {
					guidebook.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object userName) {
					guidebook.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object createDate) {
					guidebook.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object modifiedDate) {
					guidebook.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object name) {
					guidebook.setName((String)name);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object status) {
					guidebook.setStatus((Integer)status);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserId",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getStatusByUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserId",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object statusByUserId) {
					guidebook.setStatusByUserId((Long)statusByUserId);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserName",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getStatusByUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserName",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(
					Guidebook guidebook, Object statusByUserName) {

					guidebook.setStatusByUserName((String)statusByUserName);
				}

			});
		attributeGetterFunctions.put(
			"statusDate",
			new Function<Guidebook, Object>() {

				@Override
				public Object apply(Guidebook guidebook) {
					return guidebook.getStatusDate();
				}

			});
		attributeSetterBiConsumers.put(
			"statusDate",
			new BiConsumer<Guidebook, Object>() {

				@Override
				public void accept(Guidebook guidebook, Object statusDate) {
					guidebook.setStatusDate((Date)statusDate);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getGuidebookId() {
		return _guidebookId;
	}

	@Override
	public void setGuidebookId(long guidebookId) {
		_guidebookId = guidebookId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Guidebook.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Guidebook.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Guidebook toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GuidebookImpl guidebookImpl = new GuidebookImpl();

		guidebookImpl.setUuid(getUuid());
		guidebookImpl.setGuidebookId(getGuidebookId());
		guidebookImpl.setGroupId(getGroupId());
		guidebookImpl.setCompanyId(getCompanyId());
		guidebookImpl.setUserId(getUserId());
		guidebookImpl.setUserName(getUserName());
		guidebookImpl.setCreateDate(getCreateDate());
		guidebookImpl.setModifiedDate(getModifiedDate());
		guidebookImpl.setName(getName());
		guidebookImpl.setStatus(getStatus());
		guidebookImpl.setStatusByUserId(getStatusByUserId());
		guidebookImpl.setStatusByUserName(getStatusByUserName());
		guidebookImpl.setStatusDate(getStatusDate());

		guidebookImpl.resetOriginalValues();

		return guidebookImpl;
	}

	@Override
	public int compareTo(Guidebook guidebook) {
		long primaryKey = guidebook.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Guidebook)) {
			return false;
		}

		Guidebook guidebook = (Guidebook)obj;

		long primaryKey = guidebook.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		GuidebookModelImpl guidebookModelImpl = this;

		guidebookModelImpl._originalUuid = guidebookModelImpl._uuid;

		guidebookModelImpl._originalGroupId = guidebookModelImpl._groupId;

		guidebookModelImpl._setOriginalGroupId = false;

		guidebookModelImpl._originalCompanyId = guidebookModelImpl._companyId;

		guidebookModelImpl._setOriginalCompanyId = false;

		guidebookModelImpl._setModifiedDate = false;

		guidebookModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Guidebook> toCacheModel() {
		GuidebookCacheModel guidebookCacheModel = new GuidebookCacheModel();

		guidebookCacheModel.uuid = getUuid();

		String uuid = guidebookCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			guidebookCacheModel.uuid = null;
		}

		guidebookCacheModel.guidebookId = getGuidebookId();

		guidebookCacheModel.groupId = getGroupId();

		guidebookCacheModel.companyId = getCompanyId();

		guidebookCacheModel.userId = getUserId();

		guidebookCacheModel.userName = getUserName();

		String userName = guidebookCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			guidebookCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			guidebookCacheModel.createDate = createDate.getTime();
		}
		else {
			guidebookCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			guidebookCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			guidebookCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		guidebookCacheModel.name = getName();

		String name = guidebookCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			guidebookCacheModel.name = null;
		}

		guidebookCacheModel.status = getStatus();

		guidebookCacheModel.statusByUserId = getStatusByUserId();

		guidebookCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = guidebookCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			guidebookCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			guidebookCacheModel.statusDate = statusDate.getTime();
		}
		else {
			guidebookCacheModel.statusDate = Long.MIN_VALUE;
		}

		return guidebookCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Guidebook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Guidebook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Guidebook, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Guidebook)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Guidebook, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Guidebook, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Guidebook, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Guidebook)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, Guidebook>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _guidebookId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private Guidebook _escapedModel;

}