/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.docs.guidebook.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Guidebook service. Represents a row in the &quot;GB_Guidebook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.docs.guidebook.model.impl.GuidebookModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.docs.guidebook.model.impl.GuidebookImpl</code>.
 * </p>
 *
 * @author liferay
 * @see Guidebook
 * @generated
 */
@ProviderType
public interface GuidebookModel
	extends BaseModel<Guidebook>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a guidebook model instance should use the {@link Guidebook} interface instead.
	 */

	/**
	 * Returns the primary key of this guidebook.
	 *
	 * @return the primary key of this guidebook
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this guidebook.
	 *
	 * @param primaryKey the primary key of this guidebook
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this guidebook.
	 *
	 * @return the uuid of this guidebook
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this guidebook.
	 *
	 * @param uuid the uuid of this guidebook
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the guidebook ID of this guidebook.
	 *
	 * @return the guidebook ID of this guidebook
	 */
	public long getGuidebookId();

	/**
	 * Sets the guidebook ID of this guidebook.
	 *
	 * @param guidebookId the guidebook ID of this guidebook
	 */
	public void setGuidebookId(long guidebookId);

	/**
	 * Returns the group ID of this guidebook.
	 *
	 * @return the group ID of this guidebook
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this guidebook.
	 *
	 * @param groupId the group ID of this guidebook
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this guidebook.
	 *
	 * @return the company ID of this guidebook
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this guidebook.
	 *
	 * @param companyId the company ID of this guidebook
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this guidebook.
	 *
	 * @return the user ID of this guidebook
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this guidebook.
	 *
	 * @param userId the user ID of this guidebook
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this guidebook.
	 *
	 * @return the user uuid of this guidebook
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this guidebook.
	 *
	 * @param userUuid the user uuid of this guidebook
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this guidebook.
	 *
	 * @return the user name of this guidebook
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this guidebook.
	 *
	 * @param userName the user name of this guidebook
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this guidebook.
	 *
	 * @return the create date of this guidebook
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this guidebook.
	 *
	 * @param createDate the create date of this guidebook
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this guidebook.
	 *
	 * @return the modified date of this guidebook
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this guidebook.
	 *
	 * @param modifiedDate the modified date of this guidebook
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this guidebook.
	 *
	 * @return the name of this guidebook
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this guidebook.
	 *
	 * @param name the name of this guidebook
	 */
	public void setName(String name);

	/**
	 * Returns the status of this guidebook.
	 *
	 * @return the status of this guidebook
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this guidebook.
	 *
	 * @param status the status of this guidebook
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this guidebook.
	 *
	 * @return the status by user ID of this guidebook
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this guidebook.
	 *
	 * @param statusByUserId the status by user ID of this guidebook
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this guidebook.
	 *
	 * @return the status by user uuid of this guidebook
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this guidebook.
	 *
	 * @param statusByUserUuid the status by user uuid of this guidebook
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this guidebook.
	 *
	 * @return the status by user name of this guidebook
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this guidebook.
	 *
	 * @param statusByUserName the status by user name of this guidebook
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this guidebook.
	 *
	 * @return the status date of this guidebook
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this guidebook.
	 *
	 * @param statusDate the status date of this guidebook
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this guidebook is approved.
	 *
	 * @return <code>true</code> if this guidebook is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this guidebook is denied.
	 *
	 * @return <code>true</code> if this guidebook is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this guidebook is a draft.
	 *
	 * @return <code>true</code> if this guidebook is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this guidebook is expired.
	 *
	 * @return <code>true</code> if this guidebook is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this guidebook is inactive.
	 *
	 * @return <code>true</code> if this guidebook is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this guidebook is incomplete.
	 *
	 * @return <code>true</code> if this guidebook is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this guidebook is pending.
	 *
	 * @return <code>true</code> if this guidebook is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this guidebook is scheduled.
	 *
	 * @return <code>true</code> if this guidebook is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Guidebook guidebook);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Guidebook> toCacheModel();

	@Override
	public Guidebook toEscapedModel();

	@Override
	public Guidebook toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}